import { createFileRoute } from "@tanstack/react-router";
import { AppShell, PageHeader } from "@/components/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileBarChart, Download, FileText, Sparkles } from "lucide-react";
import { getActiveTarget } from "@/utils/active-target";
import { llmReport } from "@/utils/llm";
import { useState } from "react";
import { toast } from "sonner";

export const Route = createFileRoute("/reports")({
  head: () => ({ meta: [{ title: "Reports — Sentinel AI" }] }),
  component: ReportsPage,
});

function ReportsPage() {
  const [activeTarget] = useState(() => getActiveTarget());
  const [reportOutput, setReportOutput] = useState<string>("");
  const [loading, setLoading] = useState(false);

  const handleGenerate = async (type: string) => {
    setLoading(true);
    try {
      const res = await llmReport({
        data: {
          type,
          target: activeTarget,
          data: `Target: ${activeTarget}. Report generation requested.`
        }
      });
      setReportOutput(res.text);
      toast.success(`${type} report generated by ${res.model}.`);
    } catch (e: any) {
      toast.error("Failed to generate report.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <AppShell>
      <PageHeader
        title="Classified Report Generator"
        description="Compile structured intelligence briefings, SITREPs, and dossier reports for leadership."
      />

      <div className="p-6 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {["Executive Brief", "Intelligence Dossier", "Daily SITREP", "Social Intel Summary", "Threat Assessment", "Media Verification Report"].map((rt) => (
            <Card key={rt} className="bg-[#111827] border-[#263548] p-4 flex items-center justify-between">
              <div>
                <div className="text-xs font-mono font-bold text-[#F3F4F6]">{rt}</div>
                <div className="text-[10px] font-mono text-[#94A3B8]">Target: {activeTarget}</div>
              </div>
              <Button size="sm" onClick={() => handleGenerate(rt)} className="bg-[#10B981] hover:bg-[#059669] text-black font-mono text-xs font-bold">
                Generate
              </Button>
            </Card>
          ))}
        </div>

        {reportOutput && (
          <Card className="bg-[#111827] border-[#263548] p-6">
            <h3 className="text-sm font-mono font-bold text-[#10B981] mb-3 flex items-center gap-2">
              <Sparkles className="size-4" />
              AI GENERATED REPORT OUTPUT (GEMINI 2.0 FLASH)
            </h3>
            <pre className="text-xs font-mono text-[#CBD5E1] whitespace-pre-wrap leading-relaxed bg-[#0B1220] p-4 rounded border border-[#263548]">
              {reportOutput}
            </pre>
          </Card>
        )}
      </div>
    </AppShell>
  );
}
