/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistsRouteImport } from './routes/watchlists'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconRouteImport } from './routes/recon'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OsintRouteImport } from './routes/osint'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as GisRouteImport } from './routes/gis'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as CrawlersRouteImport } from './routes/crawlers'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconRoute = ReconRouteImport.update({
  id: '/recon',
  path: '/recon',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OsintRoute = OsintRouteImport.update({
  id: '/osint',
  path: '/osint',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlersRoute = CrawlersRouteImport.update({
  id: '/crawlers',
  path: '/crawlers',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/crawlers': typeof CrawlersRoute
  '/entities': typeof EntitiesRoute
  '/exports': typeof ExportsRoute
  '/gis': typeof GisRoute
  '/graph': typeof GraphRoute
  '/images': typeof ImagesRoute
  '/investigations': typeof InvestigationsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/news': typeof NewsRoute
  '/osint': typeof OsintRoute
  '/profile': typeof ProfileRoute
  '/recon': typeof ReconRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/sources': typeof SourcesRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
  '/threats': typeof ThreatsRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/vault': typeof VaultRoute
  '/videos': typeof VideosRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/crawlers': typeof CrawlersRoute
  '/entities': typeof EntitiesRoute
  '/exports': typeof ExportsRoute
  '/gis': typeof GisRoute
  '/graph': typeof GraphRoute
  '/images': typeof ImagesRoute
  '/investigations': typeof InvestigationsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/news': typeof NewsRoute
  '/osint': typeof OsintRoute
  '/profile': typeof ProfileRoute
  '/recon': typeof ReconRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/sources': typeof SourcesRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
  '/threats': typeof ThreatsRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/vault': typeof VaultRoute
  '/videos': typeof VideosRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/crawlers': typeof CrawlersRoute
  '/entities': typeof EntitiesRoute
  '/exports': typeof ExportsRoute
  '/gis': typeof GisRoute
  '/graph': typeof GraphRoute
  '/images': typeof ImagesRoute
  '/investigations': typeof InvestigationsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/news': typeof NewsRoute
  '/osint': typeof OsintRoute
  '/profile': typeof ProfileRoute
  '/recon': typeof ReconRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/sources': typeof SourcesRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
  '/threats': typeof ThreatsRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/vault': typeof VaultRoute
  '/videos': typeof VideosRoute
  '/watchlists': typeof WatchlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/alerts'
    | '/crawlers'
    | '/entities'
    | '/exports'
    | '/gis'
    | '/graph'
    | '/images'
    | '/investigations'
    | '/live'
    | '/login'
    | '/network'
    | '/news'
    | '/osint'
    | '/profile'
    | '/recon'
    | '/reports'
    | '/sentiment'
    | '/settings'
    | '/social'
    | '/sources'
    | '/subjects'
    | '/tasks'
    | '/threats'
    | '/timeline'
    | '/trends'
    | '/vault'
    | '/videos'
    | '/watchlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/alerts'
    | '/crawlers'
    | '/entities'
    | '/exports'
    | '/gis'
    | '/graph'
    | '/images'
    | '/investigations'
    | '/live'
    | '/login'
    | '/network'
    | '/news'
    | '/osint'
    | '/profile'
    | '/recon'
    | '/reports'
    | '/sentiment'
    | '/settings'
    | '/social'
    | '/sources'
    | '/subjects'
    | '/tasks'
    | '/threats'
    | '/timeline'
    | '/trends'
    | '/vault'
    | '/videos'
    | '/watchlists'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/alerts'
    | '/crawlers'
    | '/entities'
    | '/exports'
    | '/gis'
    | '/graph'
    | '/images'
    | '/investigations'
    | '/live'
    | '/login'
    | '/network'
    | '/news'
    | '/osint'
    | '/profile'
    | '/recon'
    | '/reports'
    | '/sentiment'
    | '/settings'
    | '/social'
    | '/sources'
    | '/subjects'
    | '/tasks'
    | '/threats'
    | '/timeline'
    | '/trends'
    | '/vault'
    | '/videos'
    | '/watchlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRoute
  CrawlersRoute: typeof CrawlersRoute
  EntitiesRoute: typeof EntitiesRoute
  ExportsRoute: typeof ExportsRoute
  GisRoute: typeof GisRoute
  GraphRoute: typeof GraphRoute
  ImagesRoute: typeof ImagesRoute
  InvestigationsRoute: typeof InvestigationsRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  NewsRoute: typeof NewsRoute
  OsintRoute: typeof OsintRoute
  ProfileRoute: typeof ProfileRoute
  ReconRoute: typeof ReconRoute
  ReportsRoute: typeof ReportsRoute
  SentimentRoute: typeof SentimentRoute
  SettingsRoute: typeof SettingsRoute
  SocialRoute: typeof SocialRoute
  SourcesRoute: typeof SourcesRoute
  SubjectsRoute: typeof SubjectsRoute
  TasksRoute: typeof TasksRoute
  ThreatsRoute: typeof ThreatsRoute
  TimelineRoute: typeof TimelineRoute
  TrendsRoute: typeof TrendsRoute
  VaultRoute: typeof VaultRoute
  VideosRoute: typeof VideosRoute
  WatchlistsRoute: typeof WatchlistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recon': {
      id: '/recon'
      path: '/recon'
      fullPath: '/recon'
      preLoaderRoute: typeof ReconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osint': {
      id: '/osint'
      path: '/osint'
      fullPath: '/osint'
      preLoaderRoute: typeof OsintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawlers': {
      id: '/crawlers'
      path: '/crawlers'
      fullPath: '/crawlers'
      preLoaderRoute: typeof CrawlersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRoute,
  CrawlersRoute: CrawlersRoute,
  EntitiesRoute: EntitiesRoute,
  ExportsRoute: ExportsRoute,
  GisRoute: GisRoute,
  GraphRoute: GraphRoute,
  ImagesRoute: ImagesRoute,
  InvestigationsRoute: InvestigationsRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  NewsRoute: NewsRoute,
  OsintRoute: OsintRoute,
  ProfileRoute: ProfileRoute,
  ReconRoute: ReconRoute,
  ReportsRoute: ReportsRoute,
  SentimentRoute: SentimentRoute,
  SettingsRoute: SettingsRoute,
  SocialRoute: SocialRoute,
  SourcesRoute: SourcesRoute,
  SubjectsRoute: SubjectsRoute,
  TasksRoute: TasksRoute,
  ThreatsRoute: ThreatsRoute,
  TimelineRoute: TimelineRoute,
  TrendsRoute: TrendsRoute,
  VaultRoute: VaultRoute,
  VideosRoute: VideosRoute,
  WatchlistsRoute: WatchlistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
